### ISSUE TITLE
El Capitan Support?

### ISSUE THREAD

**Issue by miralize** [tatey/Lighting#15] opened 2015-10-01 21:01 UTC
I can see the toggle buttons very briefly when I open the notification centre, but they disappear almost instantly. Have you plans on updating it for El Capitan?

**Comment by tatey** [comment] 2015-10-01 23:19
Hello!

Yes, I do plan to make this compatible with El Capitan and Yosemite. I need to update my machine first and I'm away for a wedding this weekend. Hopefully I'll be able to get this some time in the next couple of weeks. Obviously if someone else beats me to it I'll merge.

Cheers,
Tate

**Comment by tatey** [comment] 2015-10-09 12:23
Good news. I've had a poke around and worked out what's going on. Grab the [1.1.3](https://github.com/tatey/Lighting/releases/tag/1.1.3) release which adds support for El Capitan.

It should continue to work fine on Yosemite as well, but I don't have a spare machine to test it on.

Anyway, give it a shot and let me know how you go.

**Comment by miralize** [comment] 2015-10-09 19:41
I just tried it and unfortunately it didn't work.

So, I revoked my access token , generated a new one and now it wont even let me authenticate. It only says. 

"Invalid access token"

**Comment by lucymhdavies** [comment] 2015-10-09 21:08
Hmm. Works fine for me on El Capitan.

**Comment by tatey** [comment] 2015-10-10 12:05
Sorry @miralize. In trying to make it work with El Capitan I had broken login. Try grabbing [1.1.4](https://github.com/tatey/Lighting/releases/tag/1.1.4) and let me know how you go.

I'm noticing that the widget appears "frozen" after first installing. It's difficult to debug because I cannot reproduce it in the simulator. Logging and logging out of my user in OS X seems to get it into a good state again.

@lucymhdavies Glad to hear!

**Comment by tatey** [comment] 2015-10-13 09:03
Getting reports from other people that this is working fine on El Capitan. It's also working for me. Closing.

**Closed by tatey** 2015-10-13 09:03 UTC
